# reconaissance des chifres manuscrits en utilisant un reseau de neurons formé de plusieurs couches cachées

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Digit_Recognizer.csv')

In [3]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [4]:
df = np.array(df)

In [5]:
print(type(df))

<class 'numpy.ndarray'>


In [6]:
df.shape

(42000, 785)

In [7]:
labels = df[:,0]

In [8]:
labels.shape

(42000,)

In [9]:
print(labels[1000:2000])

[1 5 1 7 4 8 9 5 7 4 7 2 2 1 4 8 8 6 2 2 2 6 7 8 1 8 8 1 9 0 7 9 6 6 8 2 3
 5 4 5 4 1 3 7 1 5 0 0 8 5 3 7 6 8 2 8 4 2 3 6 2 8 7 2 4 7 3 4 4 5 4 8 3 1
 5 1 0 2 2 2 9 5 9 6 6 9 4 1 7 2 2 0 7 0 6 8 0 5 7 4 7 9 3 2 5 7 1 9 9 9 9
 4 5 5 7 6 2 6 3 1 8 5 3 3 4 7 3 2 9 7 5 5 6 9 8 0 8 3 4 9 2 0 8 6 9 1 4 2
 8 5 6 7 1 8 2 5 7 2 8 4 5 8 7 5 4 6 7 0 0 4 1 1 8 3 0 2 2 2 8 4 3 1 6 3 9
 1 4 7 9 8 8 0 1 1 6 6 9 2 3 5 6 6 6 9 8 7 2 8 5 1 2 9 0 5 7 2 2 3 1 4 2 1
 0 2 4 2 6 0 6 6 2 5 4 3 7 8 1 7 3 7 6 7 9 4 4 1 4 9 5 8 4 7 6 0 2 5 9 9 9
 0 0 2 9 6 3 5 6 1 1 7 5 3 8 3 6 2 1 9 5 9 5 0 6 8 2 0 2 2 3 8 1 4 3 4 1 4
 9 3 2 8 9 6 1 0 4 9 5 9 6 4 4 2 5 2 0 7 6 5 6 6 3 8 5 6 3 7 5 2 3 9 2 2 9
 7 7 8 3 8 7 3 1 4 8 9 6 6 2 1 7 1 8 8 5 0 6 0 0 6 7 9 6 1 4 9 9 2 9 1 9 7
 2 5 6 1 6 0 5 3 1 2 1 5 4 4 7 0 9 3 1 6 6 6 5 7 2 0 8 7 1 6 2 2 8 0 8 1 9
 0 2 1 1 1 4 1 8 1 3 7 5 2 1 9 1 4 9 6 4 6 0 6 1 7 6 1 3 1 0 2 5 9 5 6 7 7
 9 2 1 5 4 4 8 1 7 4 2 0 8 0 1 7 7 4 0 0 1 6 5 5 9 8 2 1 0 5 0 1 5 0 4 1 4
 2 8 5 4 9 1 6 9 0 0 6 3 

In [10]:
df = df[:,1:df.shape[1]]

In [11]:
df.shape

(42000, 784)

In [12]:
X_train = df[0:1000,:].T
Y_train = labels[0:1000]
print('x train shape est {}\n Y train shape est {}'.format(X_train.shape,Y_train.shape))

x train shape est (784, 1000)
 Y train shape est (1000,)


In [13]:
X_train = X_train / 255

In [14]:
print(X_train.max())
print(X_train.min())

1.0
0.0


In [15]:
print(Y_train[0:10])

[1 0 1 4 0 0 7 3 5 3]


In [16]:
def One_Hot(Y) :
    A = np.zeros((Y.shape[0],np.max(Y)+1))
    A[range(Y.shape[0]),Y] = 1
    return A.T

In [17]:
Y = One_Hot(Y_train)
Y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [18]:
# np.random.seed(seed = 30)

In [19]:
def Init_poids(N_N_L_list) :
    # N_N_L_list : est une liste des nombres de neuds de chaque couche
    # par exemple N_N_L_list = [784,15,20,10] cad couche1 contient 784 noeuds
    # couche2 contient 15 noeuds couche3 contient 20 noeuds la derniere couche 
    # contient 10 noueds
    
    nb_layers = len(N_N_L_list)
    param = {}
    
    for i in range(1, nb_layers) :
        param['theta'+str(i)] = np.random.rand(N_N_L_list[i],N_N_L_list[i-1]) - 0.5
        param['b'+str(i)] = np.random.rand(N_N_L_list[i],1) - 0.5
    
    return param

In [20]:
# param = Init_poids([8,7,5,4,3])
# for k,v in param.items() :
#     print(k,v.shape)

In [21]:
def softmax(X):
    return np.exp(X)/sum(np.exp(X))

In [22]:
def Relu(X) :
    return np.where(X>=0,X,0) 

In [23]:
Y1 = Relu(np.array([-1,3]))
Y1

array([0, 3])

In [24]:
def Rel_prime(X):
    return np.where(X<=0,0,1)

In [25]:
def Forward_propagation(param,X):
    nbr_layer = len(param) // 2 + 1
    outp = {'Z1' : X, 'A1' : X}
    for i in range(2,nbr_layer) :
        outp['Z'+str(i)] = np.dot(param['theta'+str(i-1)],outp['A'+str(i-1)])+param['b'+str(i-1)]
        outp['A'+str(i)] = Relu(outp['Z'+str(i)])
    outp['Z'+str(nbr_layer)] = np.dot(param['theta'+str(nbr_layer-1)],outp['A'+str(nbr_layer-1)])+param['b'+str(nbr_layer-1)]
    outp['A'+str(nbr_layer)] = softmax(outp['Z'+str(nbr_layer)]) 
    return outp

In [26]:
# X = np.array([[1,2],[3,4],[2,3],[5,2],[3,9],[6,3],[1,0],[3,9]])
# outp = Forward_propagation(param,X)
# for k,v in outp.items() :
#     print(k,v.shape)

In [40]:
def Backward_propagation(param,outp, X, Y):
    
    nbr_layer = len(param) // 2 + 1
    m = Y.shape[0]
    Y_enc = One_Hot(Y)
    #Y_enc = np.array([[0,1],[1,0],[0,1]])
    grad = {}
    

    delta = outp['A'+str(nbr_layer)] -Y_enc
    for i in reversed(range(2,nbr_layer)) :
        grad['dtheta' + str(i)] = 1/m * np.dot(delta, outp['A'+str(i)].T)
        grad['db' + str(i)] = 1/m * np.sum(delta, axis=1, keepdims=True)
        delta = np.dot(param['theta'+str(i)].T, delta) * Rel_prime(outp['Z'+str(i)])
    grad['dtheta' + str(1)] = 1/m * np.dot(delta, outp['A'+str(1)].T)
    grad['db' + str(1)] = 1/m * np.sum(delta, axis=1, keepdims=True)
    
    return grad

In [41]:
# Y = np.array([0,2])
# grad = Backward_propagation(param,outp, X, Y)
# for k,v in grad.items() :
#     print(k,v.shape)

In [42]:
def pred(A2) :
    return np.argmax(A2, axis=0)

In [43]:
def precision(Y_true,Y_pred) :
    return np.sum(Y_true == Y_pred)/Y_true.shape[0]

In [44]:
def update_param(param,grad,alpha) :
    nbr_layer = len(param) // 2 + 1
    
    for i in range(1,nbr_layer) :
        param['theta'+str(i)] -= alpha * grad['dtheta'+str(i)]
        param['b'+str(i)] -= alpha * grad['db'+str(i)]
    return param

In [45]:
def grad_descent(X, Y, list_neaurons, alpha, nbitr) :
    
    param = Init_poids(list_neaurons)
    nbr_layer = len(param) // 2 + 1
    for i in range(nbitr) :
        outp = Forward_propagation(param,X)
        grad = Backward_propagation(param,outp, X, Y)
        
        param = update_param(param,grad,alpha)
        
        Y_pred = pred(outp['A'+str(nbr_layer)])
        prec = precision(Y, Y_pred)
        
        if i%100 == 0 :
            print('precision a l iteration {} = {}'
              .format(i,prec))
    return param

In [48]:
param = grad_descent(X_train, Y_train, [784,15,15,5,10], 0.1, 1901) 

precision a l iteration 0 = 0.081
precision a l iteration 100 = 0.47
precision a l iteration 200 = 0.68
precision a l iteration 300 = 0.763
precision a l iteration 400 = 0.812
precision a l iteration 500 = 0.854
precision a l iteration 600 = 0.887
precision a l iteration 700 = 0.914
precision a l iteration 800 = 0.946
precision a l iteration 900 = 0.964
precision a l iteration 1000 = 0.972
precision a l iteration 1100 = 0.981
precision a l iteration 1200 = 0.982
precision a l iteration 1300 = 0.983
precision a l iteration 1400 = 0.984
precision a l iteration 1500 = 0.984
precision a l iteration 1600 = 0.984
precision a l iteration 1700 = 0.985
precision a l iteration 1800 = 0.985
precision a l iteration 1900 = 0.985
