# reconaissance des chifres manuscrits en utilisant un reseau de neurons formé de trois couches 

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Digit_Recognizer.csv')

In [4]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [5]:
df = np.array(df)

In [6]:
print(type(df))

<class 'numpy.ndarray'>


In [7]:
df.shape

(42000, 785)

In [8]:
labels = df[:,0]

In [9]:
labels.shape

(42000,)

In [10]:
print(labels[1000:2000])

[1 5 1 7 4 8 9 5 7 4 7 2 2 1 4 8 8 6 2 2 2 6 7 8 1 8 8 1 9 0 7 9 6 6 8 2 3
 5 4 5 4 1 3 7 1 5 0 0 8 5 3 7 6 8 2 8 4 2 3 6 2 8 7 2 4 7 3 4 4 5 4 8 3 1
 5 1 0 2 2 2 9 5 9 6 6 9 4 1 7 2 2 0 7 0 6 8 0 5 7 4 7 9 3 2 5 7 1 9 9 9 9
 4 5 5 7 6 2 6 3 1 8 5 3 3 4 7 3 2 9 7 5 5 6 9 8 0 8 3 4 9 2 0 8 6 9 1 4 2
 8 5 6 7 1 8 2 5 7 2 8 4 5 8 7 5 4 6 7 0 0 4 1 1 8 3 0 2 2 2 8 4 3 1 6 3 9
 1 4 7 9 8 8 0 1 1 6 6 9 2 3 5 6 6 6 9 8 7 2 8 5 1 2 9 0 5 7 2 2 3 1 4 2 1
 0 2 4 2 6 0 6 6 2 5 4 3 7 8 1 7 3 7 6 7 9 4 4 1 4 9 5 8 4 7 6 0 2 5 9 9 9
 0 0 2 9 6 3 5 6 1 1 7 5 3 8 3 6 2 1 9 5 9 5 0 6 8 2 0 2 2 3 8 1 4 3 4 1 4
 9 3 2 8 9 6 1 0 4 9 5 9 6 4 4 2 5 2 0 7 6 5 6 6 3 8 5 6 3 7 5 2 3 9 2 2 9
 7 7 8 3 8 7 3 1 4 8 9 6 6 2 1 7 1 8 8 5 0 6 0 0 6 7 9 6 1 4 9 9 2 9 1 9 7
 2 5 6 1 6 0 5 3 1 2 1 5 4 4 7 0 9 3 1 6 6 6 5 7 2 0 8 7 1 6 2 2 8 0 8 1 9
 0 2 1 1 1 4 1 8 1 3 7 5 2 1 9 1 4 9 6 4 6 0 6 1 7 6 1 3 1 0 2 5 9 5 6 7 7
 9 2 1 5 4 4 8 1 7 4 2 0 8 0 1 7 7 4 0 0 1 6 5 5 9 8 2 1 0 5 0 1 5 0 4 1 4
 2 8 5 4 9 1 6 9 0 0 6 3 

In [11]:
df = df[:,1:df.shape[1]]

In [12]:
df.shape

(42000, 784)

In [13]:
X_train = df[0:1000,:].T
Y_train = labels[0:1000]
print('x train shape est {}\n Y train shape est {}'.format(X_train.shape,Y_train.shape))

x train shape est (784, 1000)
 Y train shape est (1000,)


In [14]:
X_train = X_train / 255

In [15]:
print(X_train.max())
print(X_train.min())

1.0
0.0


In [16]:
print(Y_train[0:10])

[1 0 1 4 0 0 7 3 5 3]


In [17]:
def One_Hot(Y) :
    A = np.zeros((Y.shape[0],np.max(Y)+1))
    A[range(Y.shape[0]),Y] = 1
    return A.T

In [18]:
Y = One_Hot(Y_train)
Y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [19]:
# np.random.seed(seed = 30)

In [20]:
def Init_poids():
    
    theta1 = np.random.rand(15,784) - 0.5
    theta2 = np.random.rand(10,15) - 0.5
    b1 = np.random.rand(15,1) - 0.5
    b2 = np.random.rand(10,1) - 0.5

#     theta1 = np.zeros((15,784)) 
#     theta2 = np.zeros((10,15)) 
#     b1 = np.zeros((15,1))
#     b2 = np.zeros((10,1)) 
    
#     theta1 = np.random.randn(3,5)
#     theta2 = np.random.randn(2,3)
#     b1 = np.random.randn(3,1)
#     b2 = np.random.randn(2,1)
    
    return theta1,theta2,b1,b2

In [21]:
 theta1,theta2,b1,b2 = Init_poids()

In [22]:
def softmax(X):
    return np.exp(X)/sum(np.exp(X))

In [23]:
def Relu(X) :
    return np.where(X>=0,X,0) 

In [24]:
Y1 = Relu(np.array([-1,3]))
Y1

array([0, 3])

In [25]:
def Rel_prime(X):
    return np.where(X<=0,0,1)

In [26]:
def Forward_propagation(theta1,b1,theta2,b2,X):
    Z1 = np.dot(theta1,X)+b1
    A1 = Relu(Z1)
    Z2 = np.dot(theta2,A1)+b2
    A2 = softmax(Z2) 
    return Z1,Z2,A1,A2

In [27]:
def Backward_propagation(theta1, theta2, A1, A2, 
                         Z1, Z2 , X, Y):
    m = Y.shape[0]
    Y_enc = One_Hot(Y)
    delta2 = A2 -Y_enc
    
    d_J_th2 = 1/m * np.dot(delta2, A1.T)
    d_J_b2 = 1/m * np.sum(delta2, axis=1, 
                          keepdims=True)
    
    delta1 = np.dot(theta2.T, delta2) * Rel_prime(Z1)
    
    d_J_th1 = 1/m * np.dot(delta1, X.T)
    d_J_b1 = 1/m * np.sum(delta1, axis=1, keepdims=True)
    
    return d_J_th1, d_J_th2, d_J_b1, d_J_b2

In [28]:
def pred(A2) :
    return np.argmax(A2, axis=0)

In [29]:
def precision(Y_true,Y_pred) :
    return np.sum(Y_true == Y_pred)/Y_true.shape[0]

In [31]:
def grad_descent(X, Y, alpha, nbitr) :
    theta1,theta2,b1,b2 = Init_poids()
    for i in range(nbitr) :
        Z1,Z2,A1,A2 = Forward_propagation(theta1,b1,
                                          theta2,b2,X)
        d_J_th1, d_J_th2, d_J_b1, d_J_b2 = Backward_propagation(theta1, theta2, A1, A2, Z1, Z2 
                             , X, Y)
        theta1 = theta1 - alpha * d_J_th1
        theta2 = theta2 - alpha * d_J_th2
        b1 = b1 - alpha * d_J_b1
        b2 = b2 - alpha * d_J_b2
        
#         print(d_J_th1[0:5,1])
#         print(d_J_th2[0:5,1])
        
#         print(theta1[0:5,1])
#         print(theta2[0:5,1])
        Y_pred = pred(A2)
        prec = precision(Y, Y_pred)
        
        if i%100 == 0 :
            print('precision a l iteration {} = {}'
              .format(i,prec))
    return theta1, theta2, b1, b2

In [35]:
theta1, theta2, b1, b2 = grad_descent(X_train, Y_train, 0.1, 1901)

precision a l iteration 0 = 0.091
precision a l iteration 100 = 0.701
precision a l iteration 200 = 0.816
precision a l iteration 300 = 0.866
precision a l iteration 400 = 0.905
precision a l iteration 500 = 0.922
precision a l iteration 600 = 0.934
precision a l iteration 700 = 0.948
precision a l iteration 800 = 0.959
precision a l iteration 900 = 0.972
precision a l iteration 1000 = 0.98
precision a l iteration 1100 = 0.989
precision a l iteration 1200 = 0.994
precision a l iteration 1300 = 0.998
precision a l iteration 1400 = 0.998
precision a l iteration 1500 = 0.998
precision a l iteration 1600 = 0.998
precision a l iteration 1700 = 0.999
precision a l iteration 1800 = 1.0
precision a l iteration 1900 = 1.0


In [ ]:
# def grad_descent_1(X, Y, alpha, nbitr, theta1,theta2,b1,b2) :
# #     theta1,theta2,b1,b2 = Init_poids()
#     for i in range(nbitr) :
#         Z1,Z2,A1,A2 = Forward_propagation(theta1,b1,
#                                           theta2,b2,X)
#         d_J_th1, d_J_th2, d_J_b1, d_J_b2 = Backward_propagation(theta1, theta2, A1, A2, Z1, Z2 
#                              , X, Y)
#         theta1 = theta1 - alpha * d_J_th1
#         theta2 = theta2 - alpha * d_J_th2
#         b1 = b1 - alpha * d_J_b1
#         b2 = b2 - alpha * d_J_b2
        
# #         print(d_J_th1[0:5,1])
# #         print(d_J_th2[0:5,1])
        
# #         print(theta1[0:5,1])
# #         print(theta2[0:5,1])
#         Y_pred = pred(A2)
#         prec = precision(Y, Y_pred)
        
#         if i%100 == 0 :
#             print('precision a l iteration {} = {}'
#               .format(i,prec))
#     return theta1, theta2, b1, b2

In [ ]:
# grad_descent_1(X_train, Y_train, 0.01, 200, theta1,theta2,b1,b2)  